// Builds the pre-generated pool of Daily Challenge puzzles (offline, recipes in
// scripts/poolGenerators.ts). Two modes:
//
//   npx tsx scripts/buildDailyPool.ts --slot 1|2|3 --size 3x4 --count 10 [--ms 120000] [--tag a]
//       Generates puzzles and appends each one immediately to
//       scripts/pool-out/slot<N>-<RxC>-<tag>.json (so a kill/timeout loses nothing;
//       use different --tag values to run several processes in parallel).
//
//   npx tsx scripts/buildDailyPool.ts --merge
//       Folds every scripts/pool-out/*.json into src/game/dailyPool.generated.ts
//       (deduplicated, ids assigned), which the app reads.
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { COLOR_PAIRS, generateSlot1, generateSlot2, generateSlot3, type PoolPuzzle } from "./poolGenerators";

const OUT_DIR = "scripts/pool-out";
const POOL_FILE = "src/game/dailyPool.generated.ts";
const MAX_UNPROVEN_MOVES = 25;
const args = process.argv.slice(2);
const arg = (name: string, fallback?: string) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : fallback;
};

function serialize(p: PoolPuzzle): string {
  return p.level.cells.map((row) => row.map((c) => (c.kind === "empty" ? "." : c.kind === "dead" ? "#" : `${c.kind[0]}${c.color}`)).join(",")).join("|");
}

if (args.includes("--merge")) {
  const groups: Record<string, PoolPuzzle[]> = {};
  const seen = new Set<string>();
  for (const file of readdirSync(OUT_DIR).filter((f) => f.endsWith(".json")).sort()) {
    const m = /^slot(\d)-(\d+x\d+)-/.exec(file);
    if (!m) continue;
    const groupKey = `${m[1]}-${m[2]}`;
    for (const p of JSON.parse(readFileSync(`${OUT_DIR}/${file}`, "utf-8")) as PoolPuzzle[]) {
      // An unproven bound this long is mostly search meandering, not a real best score — skip it.
      if (!p.proven && p.optimal > MAX_UNPROVEN_MOVES) continue;
      const s = serialize(p);
      if (seen.has(s)) continue;
      seen.add(s);
      (groups[groupKey] ??= []).push(p);
    }
  }
  const pool: Record<string, unknown[]> = {};
  const best: Record<string, { moves: number; proven: boolean }> = {};
  for (const [g, list] of Object.entries(groups)) {
    pool[g] = list.map((p, i) => {
      const id = `d${g}-${String(i + 1).padStart(3, "0")}`;
      best[id] = { moves: p.optimal, proven: p.proven };
      return { ...p.level, id };
    });
    console.log(`${g}: ${list.length} puzzles (${list.filter((p) => p.proven).length} proven)`);
  }
  writeFileSync(
    POOL_FILE,
    `// AUTO-GENERATED by scripts/buildDailyPool.ts --merge — pre-validated Daily Challenge pool.
// Keys are "<slot>-<rows>x<cols>". Do not edit by hand; rebuild instead.
import type { Level } from "./types";

export const dailyPool: Record<string, Level[]> = ${JSON.stringify(pool, null, 2)};

export const dailyPoolBest: Record<string, { moves: number; proven: boolean }> = ${JSON.stringify(best, null, 2)};
`,
    "utf-8",
  );
  console.log(`Wrote ${POOL_FILE}`);
} else {
  const slot = Number(arg("--slot"));
  const [rows, cols] = (arg("--size", "5x5") as string).split("x").map(Number);
  const count = Number(arg("--count", "10"));
  const ms = Number(arg("--ms", "120000"));
  const tag = arg("--tag", "a");
  if (![1, 2, 3].includes(slot)) throw new Error("--slot must be 1, 2 or 3");
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  const outFile = `${OUT_DIR}/slot${slot}-${rows}x${cols}-${tag}.json`;
  const results: PoolPuzzle[] = existsSync(outFile) ? JSON.parse(readFileSync(outFile, "utf-8")) : [];
  const offset = Math.floor(Math.random() * 3);

  for (let i = 0; i < count; i++) {
    const started = Date.now();
    const colors = COLOR_PAIRS[(i + offset) % COLOR_PAIRS.length];
    const puzzle = slot === 1 ? generateSlot1(rows, cols, colors, ms) : slot === 2 ? generateSlot2(rows, cols, colors, ms) : generateSlot3(ms);
    const secs = Math.round((Date.now() - started) / 100) / 10;
    if (!puzzle) {
      console.log(`${i + 1}/${count}: gave up after ${secs}s`);
      continue;
    }
    results.push(puzzle);
    writeFileSync(outFile, JSON.stringify(results), "utf-8"); // save immediately
    console.log(`${i + 1}/${count}: optimal ${puzzle.optimal}${puzzle.proven ? "" : "+"} in ${secs}s`);
  }
  console.log(`${results.length} puzzles in ${outFile}`);
}
